# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-28 20:18
from __future__ import unicode_literals

import apps.image_uploader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.image_uploader.models.path_and_rename),
        ),
    ]
