# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-27 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='users',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
    ]
