# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-08-28 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flash_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
